### ISSUE TITLE
Make gem compatible with rails 4.1

### ISSUE THREAD

**Issue by arthurnn** [arthurnn/apn_sender#67]

**Comment by lukeasrodgers** [comment]
It seems like there isn't much preventing the relaxation of the `< 4.1.0` restriction. 

However, it also appears that some of the notification specs related to truncating the error message do not currently pass with activesupport 3.x.x, due to the change here: https://github.com/rails/rails/commit/80e7552073712e102c584cfc54cb3eff2c1f0f52. Prior to this change, utf8 chars would be escaped (e.g. "é" -> "\"\\u00e9\"") which results in oversize payloads that appear un-truncatable. The current truncation algorithm only passes the specs with activesupport 4.x.x), AFAICT.

I think a fix is possible that would more or less preserve the behaviour for activesupport 3.x.x but it's a bit ugly (involves checking AS version, and a couples changes to the tests).

**Comment by arthurnn** [comment]
@lukeasrodgers if you want to give it a try on the fix and send a PR, I would review it.
thanks
